server:
  port: 8080

zipcode:
  client:
    address:
      url: http://localhost:8082/addresses

spring:
  data:
    mongodb:
      host: localhost
      port: 27018
      authentication-database: admin
      username: root
      password: password
      database: hex